### ISSUE TITLE
VSTS Build #49 succeded but it actually failed to build any code

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [timbircode/minicloner#66]
VSTS build 49 with commit 3b36b54a6ccf81eec434ad24c5efe549945563d7 and issue #65  succeded but in reality it failed to use .net core SDK 1.0, and it failed to recognize this failure because the return code returned by cake's `StartProcess` that calls `dotnet build`  is being ignored.

The following is the build's log:

```
2017-03-12T16:03:52.0345918Z ##[section]Starting: Build
2017-03-12T16:03:52.0502158Z Current agent version: '2.112.0'
2017-03-12T16:03:52.7545649Z Downloading task: PowerShell
2017-03-12T16:03:53.1830701Z Downloading task: Cake
2017-03-12T16:03:53.3493837Z Downloading task: PublishTestResults
2017-03-12T16:03:55.5561363Z ##[section]Starting: Get Sources
2017-03-12T16:03:55.6754051Z Syncing repository: carlosmunozrodriguez/minicloner (GitHub)
2017-03-12T16:03:55.6754051Z Prepending Path environment variable with directory containing 'git.exe'.
2017-03-12T16:03:55.7225363Z ##[command]git version
2017-03-12T16:03:56.0697101Z ##[command]git init "D:\a\1\s"
2017-03-12T16:03:56.1478353Z Initialized empty Git repository in D:/a/1/s/.git/
2017-03-12T16:03:56.1478353Z ##[command]git remote add origin https://github.com/carlosmunozrodriguez/minicloner.git
2017-03-12T16:03:56.1790923Z ##[command]git config gc.auto 0
2017-03-12T16:03:56.2103428Z ##[command]git config --get-all http.https://github.com/carlosmunozrodriguez/minicloner.git.extraheader
2017-03-12T16:03:56.2415873Z ##[command]git config --get-all http.proxy
2017-03-12T16:03:56.2884634Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ********" fetch --tags --prune --progress origin
2017-03-12T16:03:57.1582068Z remote: Counting objects: 588, done.        
2017-03-12T16:03:57.1582068Z remote: Compressing objects:   6% (1/16)           
2017-03-12T16:03:57.1582068Z remote: Compressing objects:  12% (2/16)           
2017-03-12T16:03:57.1582068Z remote: Compressing objects:  18% (3/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  25% (4/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  31% (5/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  37% (6/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  43% (7/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  50% (8/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  56% (9/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  62% (10/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  68% (11/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  75% (12/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  81% (13/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  87% (14/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects:  93% (15/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects: 100% (16/16)           
2017-03-12T16:03:57.1737630Z remote: Compressing objects: 100% (16/16), done.        
2017-03-12T16:03:57.1894058Z Receiving objects:   0% (1/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   1% (6/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   2% (12/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   3% (18/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   4% (24/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   5% (30/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   6% (36/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   7% (42/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   8% (48/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:   9% (53/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  10% (59/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  11% (65/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  12% (71/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  13% (77/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  14% (83/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  15% (89/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  16% (95/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  17% (100/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  18% (106/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  19% (112/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  20% (118/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  21% (124/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  22% (130/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  23% (136/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  24% (142/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  25% (147/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  26% (153/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  27% (159/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  28% (165/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  29% (171/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  30% (177/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  31% (183/588)   
2017-03-12T16:03:57.1894058Z Receiving objects:  32% (189/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  33% (195/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  34% (200/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  35% (206/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  36% (212/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  37% (218/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  38% (224/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  39% (230/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  40% (236/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  41% (242/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  42% (247/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  43% (253/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  44% (259/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  45% (265/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  46% (271/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  47% (277/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  48% (283/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  49% (289/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  50% (294/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  51% (300/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  52% (306/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  53% (312/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  54% (318/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  55% (324/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  56% (330/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  57% (336/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  58% (342/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  59% (347/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  60% (353/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  61% (359/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  62% (365/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  63% (371/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  64% (377/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  65% (383/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  66% (389/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  67% (394/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  68% (400/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  69% (406/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  70% (412/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  71% (418/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  72% (424/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  73% (430/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  74% (436/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  75% (441/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  76% (447/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  77% (453/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  78% (459/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  79% (465/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  80% (471/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  81% (477/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  82% (483/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  83% (489/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  84% (494/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  85% (500/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  86% (506/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  87% (512/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  88% (518/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  89% (524/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  90% (530/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  91% (536/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  92% (541/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  93% (547/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  94% (553/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  95% (559/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  96% (565/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  97% (571/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  98% (577/588)   
2017-03-12T16:03:57.2056060Z Receiving objects:  99% (583/588)   
2017-03-12T16:03:57.2056060Z Receiving objects: 100% (588/588)   
2017-03-12T16:03:57.2056060Z Receiving objects: 100% (588/588), 90.55 KiB | 0 bytes/s, done.
2017-03-12T16:03:57.2056060Z remote: Total 588 (delta 1), reused 0 (delta 0), pack-reused 570        
2017-03-12T16:03:57.2056060Z Resolving deltas:   0% (0/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   1% (4/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   2% (7/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   3% (11/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   6% (21/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   7% (25/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   8% (30/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:   9% (32/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  10% (38/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  11% (40/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  12% (42/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  13% (46/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  14% (52/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  15% (54/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  16% (56/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  17% (61/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  22% (79/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  23% (82/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  28% (99/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  29% (102/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  31% (108/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  36% (127/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  39% (137/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  44% (154/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  47% (165/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  50% (174/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  51% (179/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  52% (184/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  54% (188/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  55% (193/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  56% (195/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  60% (209/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  61% (215/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  62% (218/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  63% (220/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  64% (225/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  65% (228/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  66% (231/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  68% (237/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  69% (242/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  70% (246/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  71% (248/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  76% (266/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  84% (293/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  85% (298/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  87% (305/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  88% (308/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  89% (313/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  90% (315/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  92% (322/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  93% (324/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  96% (335/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  97% (341/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas:  99% (346/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas: 100% (348/348)   
2017-03-12T16:03:57.2056060Z Resolving deltas: 100% (348/348), done.
2017-03-12T16:03:57.2518898Z From https://github.com/carlosmunozrodriguez/minicloner
2017-03-12T16:03:57.2518898Z  * [new branch]      develop                -> origin/develop
2017-03-12T16:03:57.2518898Z  * [new branch]      feature/upgrade-vs2017 -> origin/feature/upgrade-vs2017
2017-03-12T16:03:57.2518898Z  * [new branch]      master                 -> origin/master
2017-03-12T16:03:57.2831402Z ##[command]git checkout --progress --force 86e2b8f2f474becaa48ea31160556623838e788f
2017-03-12T16:03:57.3300153Z Note: checking out '86e2b8f2f474becaa48ea31160556623838e788f'.
2017-03-12T16:03:57.3300153Z 
2017-03-12T16:03:57.3300153Z You are in 'detached HEAD' state. You can look around, make experimental
2017-03-12T16:03:57.3300153Z changes and commit them, and you can discard any commits you make in this
2017-03-12T16:03:57.3300153Z state without impacting any branches by performing another checkout.
2017-03-12T16:03:57.3300153Z 
2017-03-12T16:03:57.3300153Z If you want to create a new branch to retain commits you create, you may
2017-03-12T16:03:57.3300153Z do so (now or later) by using -b with the checkout command again. Example:
2017-03-12T16:03:57.3300153Z 
2017-03-12T16:03:57.3300153Z   git checkout -b <new-branch-name>
2017-03-12T16:03:57.3300153Z 
2017-03-12T16:03:57.3300153Z HEAD is now at 86e2b8f... Merge pull request #65 from carlosmunozrodriguez/feature/upgrade-vs2017
2017-03-12T16:03:57.3466208Z ##[section]Finishing: Get Sources
2017-03-12T16:03:57.3466208Z ##[section]Starting: dotnet --info
2017-03-12T16:03:57.3925169Z ==============================================================================
2017-03-12T16:03:57.3925169Z Task         : PowerShell
2017-03-12T16:03:57.3925169Z Description  : Run a PowerShell script
2017-03-12T16:03:57.3925169Z Version      : 1.2.2
2017-03-12T16:03:57.3925169Z Author       : Microsoft Corporation
2017-03-12T16:03:57.3925169Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2017-03-12T16:03:57.3925169Z ==============================================================================
2017-03-12T16:03:57.5331437Z ##[command]. 'C:\Users\buildguest\AppData\Local\Temp\9b137484-4a8d-46a7-be4b-afd21dde7b16.ps1' 
2017-03-12T16:03:59.8751787Z .NET Command Line Tools (1.0.0-preview2-1-003177)
2017-03-12T16:03:59.8751787Z 
2017-03-12T16:03:59.8751787Z Product Information:
2017-03-12T16:03:59.8751787Z  Version:            1.0.0-preview2-1-003177
2017-03-12T16:03:59.8751787Z  Commit SHA-1 hash:  a2df9c2576
2017-03-12T16:03:59.8751787Z 
2017-03-12T16:03:59.8751787Z Runtime Environment:
2017-03-12T16:03:59.8751787Z  OS Name:     Windows
2017-03-12T16:03:59.8751787Z  OS Version:  6.3.9600
2017-03-12T16:03:59.8751787Z  OS Platform: Windows
2017-03-12T16:04:00.0855402Z  RID:         win81-x64
2017-03-12T16:04:00.3667946Z ##[section]Finishing: dotnet --info
2017-03-12T16:04:00.3667946Z ##[section]Starting: Build
2017-03-12T16:04:00.3667946Z ==============================================================================
2017-03-12T16:04:00.3667946Z Task         : Cake
2017-03-12T16:04:00.3667946Z Description  : Build with Cake
2017-03-12T16:04:00.3667946Z Version      : 0.2.4
2017-03-12T16:04:00.3667946Z Author       : Patrik Svensson
2017-03-12T16:04:00.3667946Z Help         : [More Information about Cake](http://cakebuild.net)
2017-03-12T16:04:00.3667946Z ==============================================================================
2017-03-12T16:04:00.3824137Z Preparing task execution handler.
2017-03-12T16:04:03.7684153Z Executing the powershell script: D:\a\_tasks\Cake_b88ea9a0-7d6e-11e5-b5de-d57d652482f7\0.2.4\Cake.ps1
2017-03-12T16:04:04.7931591Z Restoring packages...
2017-03-12T16:04:04.7931591Z 
2017-03-12T16:04:04.7931591Z 
2017-03-12T16:04:05.5930210Z Installing 'Cake 0.18.0'.
2017-03-12T16:04:05.9212255Z Successfully installed 'Cake 0.18.0'.
2017-03-12T16:04:05.9367740Z Executing build script...
2017-03-12T16:04:05.9367740Z 
2017-03-12T16:04:05.9367740Z 
2017-03-12T16:04:05.9680265Z D:\a\1\s\tools\Cake\Cake.exe "D:\a\1\s\build.cake" -target="Default" -verbosity="Verbose" --paths_tools="D:\a\1\s\tools" 
2017-03-12T16:04:06.3117817Z Analyzing build script...
2017-03-12T16:04:06.3274108Z Processing build script...
2017-03-12T16:04:06.3430621Z Downloading and installing Roslyn...
2017-03-12T16:04:06.5833461Z Installing packages (using https://packages.nuget.org/api/v2)...
2017-03-12T16:04:08.4530038Z Copying files...
2017-03-12T16:04:08.4530038Z Copying Roslyn.Compilers.CSharp.dll...
2017-03-12T16:04:08.4530038Z Copying Roslyn.Compilers.dll...
2017-03-12T16:04:08.4530038Z Deleting installation directory...
2017-03-12T16:04:08.8662637Z Compiling build script...
2017-03-12T16:04:12.6318061Z 
2017-03-12T16:04:12.6318061Z ========================================
2017-03-12T16:04:12.6318061Z Restore
2017-03-12T16:04:12.6318061Z ========================================
2017-03-12T16:04:12.6318061Z Executing task: Restore
2017-03-12T16:04:13.2067547Z warn : The folder 'D:\a\1\s' does not contain a project to restore.
2017-03-12T16:04:13.2536528Z Finished executing task: Restore
2017-03-12T16:04:13.2536528Z 
2017-03-12T16:04:13.2536528Z ========================================
2017-03-12T16:04:13.2536528Z Build
2017-03-12T16:04:13.2536528Z ========================================
2017-03-12T16:04:13.2536528Z Executing task: Build
2017-03-12T16:04:13.3317505Z Specify --help for a list of available options and commands.
2017-03-12T16:04:13.3630013Z ##[error]Unrecognized option '--verbosity'
2017-03-12T16:04:13.3630013Z Finished executing task: Build
2017-03-12T16:04:13.3630013Z 
2017-03-12T16:04:13.3630013Z ========================================
2017-03-12T16:04:13.3630013Z Test
2017-03-12T16:04:13.3630013Z ========================================
2017-03-12T16:04:13.3630013Z Executing task: Test
2017-03-12T16:04:13.8006244Z ##[error]dotnet-test Error: 0 : System.InvalidOperationException: test/Minicloner.Tests/Minicloner.Tests.csproj\project.json does not exist.
2017-03-12T16:04:13.8006244Z ##[error]   at Microsoft.DotNet.Tools.Test.TestCommand.GetProjectPath(String projectPath)
2017-03-12T16:04:13.8006244Z ##[error]   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
2017-03-12T16:04:13.8006244Z Finished executing task: Test
2017-03-12T16:04:13.8006244Z 
2017-03-12T16:04:13.8006244Z ========================================
2017-03-12T16:04:13.8006244Z Default
2017-03-12T16:04:13.8006244Z ========================================
2017-03-12T16:04:13.8006244Z Executing task: Default
2017-03-12T16:04:13.8006244Z Finished executing task: Default
2017-03-12T16:04:13.8161323Z 
2017-03-12T16:04:13.8161323Z Task                          Duration            
2017-03-12T16:04:13.8161323Z --------------------------------------------------
2017-03-12T16:04:13.8161323Z Restore                       00:00:00.6283429    
2017-03-12T16:04:13.8161323Z Build                         00:00:00.0900428    
2017-03-12T16:04:13.8161323Z Test                          00:00:00.4641506    
2017-03-12T16:04:13.8161323Z Default                       00:00:00.0002892    
2017-03-12T16:04:13.8161323Z --------------------------------------------------
2017-03-12T16:04:13.8161323Z Total:                        00:00:01.1828255    
2017-03-12T16:04:13.8630069Z ##[section]Finishing: Build
2017-03-12T16:04:13.8630069Z ##[section]Starting: Publish Test Results
2017-03-12T16:04:13.8786336Z ==============================================================================
2017-03-12T16:04:13.8786336Z Task         : Publish Test Results
2017-03-12T16:04:13.8786336Z Description  : Publish Test Results to VSTS/TFS
2017-03-12T16:04:13.8786336Z Version      : 1.0.36
2017-03-12T16:04:13.8786336Z Author       : Microsoft Corporation
2017-03-12T16:04:13.8786336Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613742)
2017-03-12T16:04:13.8786336Z ==============================================================================
2017-03-12T16:04:13.8786336Z Preparing task execution handler.
2017-03-12T16:04:14.3473885Z Executing the powershell script: D:\a\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.36\PublishTestResults.ps1
2017-03-12T16:04:14.9411471Z Publishing Test Results...
2017-03-12T16:04:16.5922341Z ##[warning]Failed to publish test results: Could not find a part of the path 'D:\a\1\s\test\Minicloner.Tests\TestResults\TestResults.trx'.
2017-03-12T16:04:16.6234855Z ##[section]Finishing: Publish Test Results
2017-03-12T16:04:16.6234855Z ##[section]Starting: Post Job Cleanup
2017-03-12T16:04:16.6234855Z Cleaning any cached credential from repository: carlosmunozrodriguez/minicloner (Git)
2017-03-12T16:04:16.6391096Z ##[command]git remote set-url origin https://github.com/carlosmunozrodriguez/minicloner.git
2017-03-12T16:04:16.6703599Z ##[command]git remote set-url --push origin https://github.com/carlosmunozrodriguez/minicloner.git
2017-03-12T16:04:16.7016092Z ##[section]Finishing: Post Job Cleanup
2017-03-12T16:04:16.7172342Z ##[section]Finishing: Build

```
Although it looks like it succeeded

![Build #49](https://i.stack.imgur.com/gLAFr.png)

The following needs to be done:

1. Change `build.cake` to actually fail when StartProcess returns an return code different than 0.
    After this change the build should fail correctly because of the incorrect arguments passed to `dotnet` commands

2. Change the build definition to actually use .net core SDK 1.0
    After this change the build should finish correctly and unit test results should be published to VSTS

**Comment by carlosmunozrodriguez** [comment]
Related to e874f7e90914399cbaef166c3663769f1562b493

**Comment by carlosmunozrodriguez** [comment]
Related to e87cea81f39aa5f9486f12a076cbf2f569876645

**Comment by carlosmunozrodriguez** [comment]
Build 50 failed (This is the expected behavior)

**Comment by carlosmunozrodriguez** [comment]
Build 52 failed since it couldn't change User path env variable, so later steps didn't use the production .net core SDK that has been installed

**Comment by carlosmunozrodriguez** [comment]
Build 61 succeeded after replacing cake with powershell (#70)

**Comment by carlosmunozrodriguez** [comment]
Build 61 succeeded after replacing cake with powershell (#70)
